name: CI Breezy

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances back
        run: npm ci
        working-directory: breezy-back

      - name: Lancer les tests back
        run: npm test
        working-directory: breezy-back

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances front
        run: npm ci
        working-directory: breezy-front

      - name: Linter
        run: npm run lint
        working-directory: breezy-front

      - name: Lancer les tests front
        run: npm test
        working-directory: breezy-front