name: Analyse SonarCloud

on:
  push:
    branches: [ "main", "master", "dev", "feat/SonarQube" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan SonarCloud
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kazerequiem
            -Dsonar.organization=kazerequiem